version: "3.9"
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "8888:6379"
  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "6222:6222"
      # - "8222:8222"
    restart: always